<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bbva.gl.kbtq</groupId>
        <artifactId>codatakbtqcddeconinformati</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>testAT</artifactId>
    <packaging>jar</packaging>

    <name>cbtq-co-spk-out-datacbtqcddeconinformation Acceptance Tests</name>

    <properties>
        <cucumber.version>5.6.0</cucumber.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.bbva.gl.kbtq</groupId>
            <artifactId>cddGlobalEcoInformation</artifactId>
            <version>0.1.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-functions</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-io</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-schema</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-datiosparksession</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.dataproc.sdk</groupId>
            <artifactId>dataproc-sdk-datiofilesystem</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.binary.version}</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.binary.version}</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datio.spark.bdt</groupId>
            <artifactId>spark-bdt</artifactId>
            <version>${datio-spark-bdt.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-scala_${scala.binary.version}</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.binary.version}</artifactId>
            <version>${scalatest.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-hive_${scala.binary.version}</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-Dspark.master=local[*]
                        -Dspark.sql.legacy.parquet.int96RebaseModeInRead=LEGACY
                        -Dspark.sql.legacy.parquet.int96RebaseModeInWrite=LEGACY
                        -Dspark.sql.legacy.parquet.datetimeRebaseModeInRead=LEGACY
                        -Dspark.sql.legacy.parquet.datetimeRebaseModeInWrite=LEGACY
                        -Dspark.sql.legacy.avro.datetimeRebaseModeInRead=LEGACY
                        -Dspark.sql.legacy.avro.datetimeRebaseModeInWrite=LEGACY
                        -Dspark.sql.legacy.avro.int96RebaseModeInRead=LEGACY
                        -Dspark.sql.legacy.avro.int96RebaseModeInWrite=LEGACY
                        -Dspark.sql.legacy.timeParserPolicy=LEGACY
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
