kirby {
    input {
        type = "custom"
        class: "com.bbva.projectsdatio.cdd.input.NoInput"
        paths = ["any"]
        schema {
            path = ${ARTIFACTORY_UNIQUE_CACHE}"/artifactory/"${SCHEMAS_REPOSITORY}"/schemas/co/kbtq/master/t_kbtq_eom_econ_information/latest/t_kbtq_eom_econ_information.output.schema"
        }
    }
    output {
        type = "custom"
        class: "com.bbva.projectsdatio.cdd.output.NoOutput"
        path = "epsilon://epsilon.live-02.ether.igrupobbva/ns/co.kbtq.app-id-12852.pro/buckets/t_kbtq_eom_econ_information/files/t_kbtq_eom_econ_information_"${?LAST_BUSINESS_DAY_MONTH_STRING}".ctl"
        schema {
            path = ${ARTIFACTORY_UNIQUE_CACHE}"/artifactory/"${SCHEMAS_REPOSITORY}"/schemas/co/kbtq/master/t_kbtq_eom_econ_information/latest/t_kbtq_eom_econ_information.output.schema"
        }
        options {
            ctlFile = true
            ctlName = "t_kbtq_eom_econ_information_"${?LAST_BUSINESS_DAY_MONTH_STRING}".ctl"
        }
    }
    transformations = []
}
