CTLGenerator {
	system = "epsilon"
	path = "epsilon://epsilon.live-02.ether.igrupobbva/ns/co.kbtq.app-id-12852.pro/buckets/t_kbtq_eom_econ_information/files/"
	fileName = "t_kbtq_eom_econ_information_"${?LAST_BUSINESS_DAY_MONTH_STRING}
	emptyCtl = "true"
	originFile = ""
	ctlDate = ""
	originFileType = ""
}