<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.datio</groupId>
        <artifactId>spark-pom-parent</artifactId>
        <version>2.0.0-3.1</version>
    </parent>

    <groupId>com.bbva.gl.kbtq</groupId>
    <artifactId>codatakbtqcddeconinformati</artifactId>
    <packaging>pom</packaging>
    <version>0.1.0-SNAPSHOT</version>

    <name>Parent codatakbtqcddeconinformati</name>

    <properties>
        <datio-spark-bdt.version>1.0.2-3.1</datio-spark-bdt.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.datio.dataproc.sdk</groupId>
                <artifactId>dataproc-sdk-bom</artifactId>
                <version>0.4.9-3.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
            </plugins>
        </pluginManagement>

        <plugins>
        </plugins>
    </build>

    <modules>
        <module>cddGlobalEcoInformation</module>
        <module>testAT</module>
    </modules>
</project>
