# Default config file for Spark Scala job process
config {
  # Config for KbtqGlSpkOutCodatakbtqcddeconinformati
    inputs = [
        {
            name = "olympics"
            fullpath = ${?EPSILON_PROTOCOL_INTERNAL_URL}/ns/ecs.dataproc/buckets/test-bucket/files/olympics.csv
            fullpath = ${?INPUT_PATH}
            uri_schema = ${?EPSILON_PROTOCOL_INTERNAL_URL}/ns/ecs.dataproc/buckets/test-bucket/files/inputSchema.json
            uri_schema = ${?INPUT_SCHEMA_PATH}
        }
    ]
    outputs = [
        {
            name = "olympicsFiltered"
            fullpath = ""
            fullpath = ${?OUTPUT_PATH}
            uri_schema = ${?EPSILON_PROTOCOL_INTERNAL_URL}/ns/ecs.dataproc/buckets/test-bucket/files/outputSchema.json
            uri_schema = ${?OUTPUT_SCHEMA_PATH}
        }
    ]
    job {
        key = "value1"
    }
}
